services:
  # --- SERVICE 1 : DAGSTER ---
  dagster-platform:
    build: .
    restart: always
    ports:
      - '3000:3000'
    environment:
      DAGSTER_POSTGRES_USER: '${DAGSTER_POSTGRES_USER}'
      DAGSTER_POSTGRES_PASSWORD: '${DAGSTER_POSTGRES_PASSWORD}'
      DAGSTER_POSTGRES_DB: '${DAGSTER_POSTGRES_DB}'
      DAGSTER_POSTGRES_HOST: '${DAGSTER_POSTGRES_HOST}'
      AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID}'
      AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'
      S3_ENDPOINT_URL: '${S3_ENDPOINT_URL}'
      GRPC_DNS_RESOLVER: native
    volumes:
      - 'dagster_home:/opt/dagster/dagster_home'
    networks:
      - coolify
    command: >
      sh -c "uv run dagster-webserver -h 0.0.0.0 -p 3000 -w workspace.yaml & uv run dagster-daemon run -w workspace.yaml"

  # --- SERVICE 2 : SPARK WORKER ---
  spark-worker:
    build: .
    restart: always
    ports:
      - "4000:4000"
    environment:
      AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID}'
      AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'
      S3_ENDPOINT_URL: '${S3_ENDPOINT_URL}'
      DAGSTER_POSTGRES_USER: '${DAGSTER_POSTGRES_USER}'
      DAGSTER_POSTGRES_PASSWORD: '${DAGSTER_POSTGRES_PASSWORD}'
      DAGSTER_POSTGRES_DB: '${DAGSTER_POSTGRES_DB}'
      DAGSTER_POSTGRES_HOST: '${DAGSTER_POSTGRES_HOST}'
    networks:
      - coolify
    command: uv run dagster api grpc -h 0.0.0.0 -p 4000 -f src/definitions.py

  # --- SERVICE 3 : FASTAPI ---
  api-serving:
    build: .
    restart: always
    environment:
      SERVICE_TYPE: api
      AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID}'
      AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'
      S3_ENDPOINT_URL: '${S3_ENDPOINT_URL}'
      API_DOMAIN: '${API_DOMAIN}'
    networks:
      - coolify
    labels:
      - "coolify.managed=true"
      - "traefik.enable=true"
      - "traefik.http.routers.api-serving.rule=Host(`${API_DOMAIN}`)"
      - "traefik.http.services.api-serving.loadbalancer.server.port=8000"

networks:
  coolify:
    external: true

volumes:
  dagster_home: